#!/bin/sh /etc/rc.common
# Fakefan init.d script

START=95
WORK_DIR="/etc/fake_fan"

# Real fan speed counts as `real_speed = raw_speed * 30` (from fan-allwinner.c)
FAN_SPEED=200
FAN_PWM=75

start() {
	# Initialize
	mount -o remount,rw /
	mkdir -p "$WORK_DIR"
	cd "$WORK_DIR"

	echo "$FAN_SPEED" > fan1speed
	echo "$FAN_SPEED" > fan0speed

	echo "$FAN_PWM" > pwm0_duty
	echo "$FAN_PWM" > pwm1_duty
	echo "$FAN_PWM" > pwm_duty

	# Clean if we already run this script
	umount "/sys/class/fanspeed/" > /dev/null
	mount --bind "$WORK_DIR" /sys/class/fanspeed/

	logger -t fake_fan "Fake path mounted"
}
